version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file
jobs:
          build_debug:
              <<: *android_config
              steps:
                - checkout
                - *restore_cache
                - run:
                    name: Download dependencies
                    command: ./gradlew androidDependencies
                - *save_cache
                - *export_gservices_key
                - *decode_gservices_key
                - run:
                    name: Gradle build (debug)
                    command: ./gradlew -PciBuild=true :mobile:assembleDebug :mobile:assembleAndroidTest
                - *persist_debug_workspace
                - store_artifacts:
                    path: mobile/build/outputs/apk/
                    destination: /apk/