
version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx4G
    steps:
      - checkout
      - run: echo "Mirkelam is working for you 👯"
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Download Dependencies
          command: bash ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: bash ./gradlew lint test
      - store_test_results:
                path: app/build/test-results
                destination: test-results/
      - run:
          name: Initial build
          command: bash ./gradlew clean assembleRelease --no-daemon --stacktrace
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
      - run:
          name: deploy to crashlytics
          command: bundle exec fastlane beta
      - run: echo "Mirkelam is working for you 👯"


deploy:
     machine:
       enabled: true
       working_directory: ~/code
       environment:
          JVM_OPTS: -Xmx4G
       steps:
        - run:
          name: deploy to crashlytics
          command: bundle exec fastlane beta
        - run: echo "Checking install"


workflows:
  #version: 2
   build_and_deploy:
   jobs:
   - build
   - run: echo "Checking build"

   - deploy:
     requires:
      filters:
        branches:
          only: master
