# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
generated_fastfile_id "4af1d9a6-f7d3-4577-af1d-07b1c5629f71"
default_platform(:android)

platform :android do
  before_all do |lane, options|
    @build_type = "Release"
  end

  

  desc "Assemble Test Application"
  lane :assemble_test_application do |options|
    gradle(task: "assemble", build_type: "#{@build_type}AndroidTest")
  end

  desc "Assemble Build and Test Application"
  lane :assemble do |options|
    assemble_build options
    assemble_test_application options
  end

  desc "Run unit tests"
  lane :unit_tests do |options|
    gradle(task: "test", build_type: @build_type)
  end

  desc "Run instrumentation tests"
  lane :instrumentation_tests do
    automated_test_emulator_run(
      AVD_setup_path: "fastlane/AVD_setup.json",
      AVD_recreate_new: false,
      AVD_clean_after: false,
      gradle_task: "connectedDebugAndroidTest")
  end
 
  lane :beta do
    # build the release variant
    build_android_app(task: "assembleRelease")

    # upload to Beta by Crashlytics
    crashlytics(
      # crashlytics_path: "./Pods/Crashlytics/
      # api_token: "58b92c81fe22e3cdf80a5b16681467616a377ed4",
      # build_secret: "4be5715b2a999108bf8bec198babd8fb01cafb0af08314d37c3b5b52bd901dc9"
      # ipa_path: "./app.ipa"
    )
  end

end